<?php
// Variables
return [
  "creatorName" => "AnnaNovas IT Ltd",
  "creatorUrl" => "https://annanovas.com",
  "templateName" => env('APP_NAME', 'Laravel'),
  "templateSuffix" => env('APP_NAME', 'Laravel'),
  "templateVersion" => "2.0.0",
  "templateFree" => false,
  "templateDescription" => env('APP_NAME', 'Laravel'),
  "templateKeyword" => "Dashboard, Admin Panel",
  "licenseUrl" => "#",
  "livePreview" => "#",
  "productPage" => "#",
  "support" => "#",
  "moreThemes" => "#",
  "documentation" => "#",
  "generator" => "",
  "changelog" => "#",
  "repository" => "#",
  "gitRepo" => "#",
  "gitRepoAccess" => "#",
  "githubFreeUrl" => "#",
  "facebookUrl" => "#",
  "twitterUrl" => "#",
  "githubUrl" => "#",
  "dribbbleUrl" => "#",
  "instagramUrl" => "#",
];
